grails-app/domain/org/eos/research/ResearchProject.groovy
package org.eos.research

class ResearchProject {


    long id
    String name
    String description
    String rewardDescription
    boolean completed = false
    Set<ResearchSkillTree> trees

    static hasMany = [trees: ResearchSkillTree]

    static constraints = {
    }

    static mapping = {
        description column: "description", sqlType: "varchar", length: 1024
        rewardDescription column: "rewardDescription", sqlType: "varchar", length: 1024
    }

}

grails-app/controllers/org/eos/research/ResearchProjectController.groovy
package org.eos.research


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ResearchProjectController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ResearchProject.list(params), model: [researchProjectInstanceCount: ResearchProject.count()]
    }

    def show(ResearchProject researchProjectInstance) {
        respond researchProjectInstance
    }

    def create() {
        respond new ResearchProject(params)
    }

    @Transactional
    def save(ResearchProject researchProjectInstance) {
        if (researchProjectInstance == null) {
            notFound()
            return
        }

        if (researchProjectInstance.hasErrors()) {
            respond researchProjectInstance.errors, view: 'create'
            return
        }

        researchProjectInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'researchProject.label', default: 'ResearchProject'), researchProjectInstance.id])
                redirect researchProjectInstance
            }
            '*' { respond researchProjectInstance, [status: CREATED] }
        }
    }

    def edit(ResearchProject researchProjectInstance) {
        respond researchProjectInstance
    }

    @Transactional
    def update(ResearchProject researchProjectInstance) {
        if (researchProjectInstance == null) {
            notFound()
            return
        }

        if (researchProjectInstance.hasErrors()) {
            respond researchProjectInstance.errors, view: 'edit'
            return
        }

        researchProjectInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ResearchProject.label', default: 'ResearchProject'), researchProjectInstance.id])
                redirect researchProjectInstance
            }
            '*' { respond researchProjectInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ResearchProject researchProjectInstance) {

        if (researchProjectInstance == null) {
            notFound()
            return
        }

        researchProjectInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ResearchProject.label', default: 'ResearchProject'), researchProjectInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'researchProject.label', default: 'ResearchProject'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/researchProject/_form.gsp
<%@ page import="org.eos.research.ResearchProject" %>



<div class="fieldcontain ${hasErrors(bean: researchProjectInstance, field: 'completed', 'error')} ">
	<label for="completed">
		<g:message code="researchProject.completed.label" default="Completed" />
		
	</label>
	<g:checkBox name="completed" value="${researchProjectInstance?.completed}" />

</div>

<div class="fieldcontain ${hasErrors(bean: researchProjectInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="researchProject.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${researchProjectInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: researchProjectInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="researchProject.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${researchProjectInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: researchProjectInstance, field: 'rewardDescription', 'error')} required">
	<label for="rewardDescription">
		<g:message code="researchProject.rewardDescription.label" default="Reward Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="rewardDescription" required="" value="${researchProjectInstance?.rewardDescription}"/>

</div>

grails-app/views/researchProject/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchProject.label', default: 'ResearchProject')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-researchProject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-researchProject" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchProjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchProjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchProjectInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/researchProject/edit.gsp
<%@ page import="org.eos.research.ResearchProject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchProject.label', default: 'ResearchProject')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-researchProject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-researchProject" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchProjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchProjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchProjectInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${researchProjectInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/researchProject/index.gsp
<%@ page import="org.eos.research.ResearchProject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchProject.label', default: 'ResearchProject')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-researchProject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-researchProject" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="completed" title="${message(code: 'researchProject.completed.label', default: 'Completed')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'researchProject.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'researchProject.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="rewardDescription" title="${message(code: 'researchProject.rewardDescription.label', default: 'Reward Description')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${researchProjectInstanceList}" status="i" var="researchProjectInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${researchProjectInstance.id}">${fieldValue(bean: researchProjectInstance, field: "completed")}</g:link></td>
					
						<td>${fieldValue(bean: researchProjectInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: researchProjectInstance, field: "name")}</td>
					
						<td>${fieldValue(bean: researchProjectInstance, field: "rewardDescription")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${researchProjectInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/researchProject/show.gsp
<%@ page import="org.eos.research.ResearchProject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchProject.label', default: 'ResearchProject')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-researchProject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-researchProject" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list researchProject">
			
				<g:if test="${researchProjectInstance?.completed}">
				<li class="fieldcontain">
					<span id="completed-label" class="property-label"><g:message code="researchProject.completed.label" default="Completed" /></span>
					
						<span class="property-value" aria-labelledby="completed-label"><g:formatBoolean boolean="${researchProjectInstance?.completed}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchProjectInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="researchProject.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${researchProjectInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchProjectInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="researchProject.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${researchProjectInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchProjectInstance?.rewardDescription}">
				<li class="fieldcontain">
					<span id="rewardDescription-label" class="property-label"><g:message code="researchProject.rewardDescription.label" default="Reward Description" /></span>
					
						<span class="property-value" aria-labelledby="rewardDescription-label"><g:fieldValue bean="${researchProjectInstance}" field="rewardDescription"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:researchProjectInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${researchProjectInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>