grails-app/domain/org/eos/research/ResearchStep.groovy
package org.eos.research

class ResearchStep {

    long id
    int level
    boolean empty = false
    StepStatus status = StepStatus.OPEN
    String quest
    String result
    Character researcher

    static constraints = {
        researcher nullable: true
        quest nullable: true
        result nullable: true
    }

    static mapping = {
        quest column: "quest", sqlType: "varchar", length: 1024
        result column: "result", sqlType: "varchar", length: 1024
    }
}

grails-app/controllers/org/eos/research/ResearchStepController.groovy
package org.eos.research


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ResearchStepController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ResearchStep.list(params), model: [researchStepInstanceCount: ResearchStep.count()]
    }

    def show(ResearchStep researchStepInstance) {
        respond researchStepInstance
    }

    def create() {
        respond new ResearchStep(params)
    }

    @Transactional
    def save(ResearchStep researchStepInstance) {
        if (researchStepInstance == null) {
            notFound()
            return
        }

        if (researchStepInstance.hasErrors()) {
            respond researchStepInstance.errors, view: 'create'
            return
        }

        researchStepInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'researchStep.label', default: 'ResearchStep'), researchStepInstance.id])
                redirect researchStepInstance
            }
            '*' { respond researchStepInstance, [status: CREATED] }
        }
    }

    def edit(ResearchStep researchStepInstance) {
        respond researchStepInstance
    }

    @Transactional
    def update(ResearchStep researchStepInstance) {
        if (researchStepInstance == null) {
            notFound()
            return
        }

        if (researchStepInstance.hasErrors()) {
            respond researchStepInstance.errors, view: 'edit'
            return
        }

        researchStepInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ResearchStep.label', default: 'ResearchStep'), researchStepInstance.id])
                redirect researchStepInstance
            }
            '*' { respond researchStepInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ResearchStep researchStepInstance) {

        if (researchStepInstance == null) {
            notFound()
            return
        }

        researchStepInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ResearchStep.label', default: 'ResearchStep'), researchStepInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'researchStep.label', default: 'ResearchStep'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/researchStep/_form.gsp
<%@ page import="org.eos.research.ResearchStep" %>



<div class="fieldcontain ${hasErrors(bean: researchStepInstance, field: 'level', 'error')} required">
	<label for="level">
		<g:message code="researchStep.level.label" default="Level" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="level" type="number" value="${researchStepInstance.level}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: researchStepInstance, field: 'quest', 'error')} required">
	<label for="quest">
		<g:message code="researchStep.quest.label" default="Quest" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="quest" required="" value="${researchStepInstance?.quest}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: researchStepInstance, field: 'result', 'error')} required">
	<label for="result">
		<g:message code="researchStep.result.label" default="Result" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="result" required="" value="${researchStepInstance?.result}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: researchStepInstance, field: 'revealed', 'error')} ">
	<label for="revealed">
		<g:message code="researchStep.revealed.label" default="Revealed" />
		
	</label>
	<g:checkBox name="revealed" value="${researchStepInstance?.revealed}" />

</div>

<div class="fieldcontain ${hasErrors(bean: researchStepInstance, field: 'solved', 'error')} ">
	<label for="solved">
		<g:message code="researchStep.solved.label" default="Solved" />
		
	</label>
	<g:checkBox name="solved" value="${researchStepInstance?.solved}" />

</div>

grails-app/views/researchStep/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchStep.label', default: 'ResearchStep')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-researchStep" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-researchStep" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchStepInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchStepInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchStepInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/researchStep/edit.gsp
<%@ page import="org.eos.research.ResearchStep" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchStep.label', default: 'ResearchStep')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-researchStep" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-researchStep" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchStepInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchStepInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchStepInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${researchStepInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/researchStep/index.gsp
<%@ page import="org.eos.research.ResearchStep" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchStep.label', default: 'ResearchStep')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-researchStep" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-researchStep" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="level" title="${message(code: 'researchStep.level.label', default: 'Level')}" />
					
						<g:sortableColumn property="quest" title="${message(code: 'researchStep.quest.label', default: 'Quest')}" />
					
						<g:sortableColumn property="result" title="${message(code: 'researchStep.result.label', default: 'Result')}" />
					
						<g:sortableColumn property="revealed" title="${message(code: 'researchStep.revealed.label', default: 'Revealed')}" />
					
						<g:sortableColumn property="solved" title="${message(code: 'researchStep.solved.label', default: 'Solved')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${researchStepInstanceList}" status="i" var="researchStepInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${researchStepInstance.id}">${fieldValue(bean: researchStepInstance, field: "level")}</g:link></td>
					
						<td>${fieldValue(bean: researchStepInstance, field: "quest")}</td>
					
						<td>${fieldValue(bean: researchStepInstance, field: "result")}</td>
					
						<td><g:formatBoolean boolean="${researchStepInstance.revealed}" /></td>
					
						<td><g:formatBoolean boolean="${researchStepInstance.solved}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${researchStepInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/researchStep/show.gsp
<%@ page import="org.eos.research.ResearchStep" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'researchStep.label', default: 'ResearchStep')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-researchStep" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-researchStep" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list researchStep">
			
				<g:if test="${researchStepInstance?.level}">
				<li class="fieldcontain">
					<span id="level-label" class="property-label"><g:message code="researchStep.level.label" default="Level" /></span>
					
						<span class="property-value" aria-labelledby="level-label"><g:fieldValue bean="${researchStepInstance}" field="level"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchStepInstance?.quest}">
				<li class="fieldcontain">
					<span id="quest-label" class="property-label"><g:message code="researchStep.quest.label" default="Quest" /></span>
					
						<span class="property-value" aria-labelledby="quest-label"><g:fieldValue bean="${researchStepInstance}" field="quest"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchStepInstance?.result}">
				<li class="fieldcontain">
					<span id="result-label" class="property-label"><g:message code="researchStep.result.label" default="Result" /></span>
					
						<span class="property-value" aria-labelledby="result-label"><g:fieldValue bean="${researchStepInstance}" field="result"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchStepInstance?.revealed}">
				<li class="fieldcontain">
					<span id="revealed-label" class="property-label"><g:message code="researchStep.revealed.label" default="Revealed" /></span>
					
						<span class="property-value" aria-labelledby="revealed-label"><g:formatBoolean boolean="${researchStepInstance?.revealed}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${researchStepInstance?.solved}">
				<li class="fieldcontain">
					<span id="solved-label" class="property-label"><g:message code="researchStep.solved.label" default="Solved" /></span>
					
						<span class="property-value" aria-labelledby="solved-label"><g:formatBoolean boolean="${researchStepInstance?.solved}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:researchStepInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${researchStepInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>