grails-app/domain/org/eos/research/Skill.groovy
package org.eos.research

class Skill {

    long id
    SkillType type
    int level
    int timesUsedOnEvent = 0

    static constraints = {
    }


    public String toString() {
        return "${type?.name} ${level}";
    }
}

grails-app/controllers/org/eos/research/SkillController.groovy
package org.eos.research


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SkillController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Skill.list(params), model: [skillInstanceCount: Skill.count()]
    }

    def show(Skill skillInstance) {
        respond skillInstance
    }

    def create() {
        respond new Skill(params)
    }

    @Transactional
    def save(Skill skillInstance) {
        println "${params}"
        println("SkillInstance: ${skillInstance}")
        if (skillInstance == null) {
            notFound()
            return
        }

        if (skillInstance.hasErrors()) {
            respond skillInstance.errors, view: 'create'
            return
        }

        skillInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'skill.label', default: 'Skill'), skillInstance.id])
                redirect skillInstance
            }
            '*' { respond skillInstance, [status: CREATED] }
        }
    }

    def edit(Skill skillInstance) {
        respond skillInstance
    }

    @Transactional
    def update(Skill skillInstance) {
        if (skillInstance == null) {
            notFound()
            return
        }

        if (skillInstance.hasErrors()) {
            respond skillInstance.errors, view: 'edit'
            return
        }

        skillInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Skill.label', default: 'Skill'), skillInstance.id])
                redirect skillInstance
            }
            '*' { respond skillInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Skill skillInstance) {

        if (skillInstance == null) {
            notFound()
            return
        }

        skillInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Skill.label', default: 'Skill'), skillInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'skill.label', default: 'Skill'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/skill/_form.gsp
<%@ page import="org.eos.research.Skill" %>



<div class="fieldcontain ${hasErrors(bean: skillInstance, field: 'level', 'error')} required">
	<label for="level">
		<g:message code="skill.level.label" default="Level" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="level" type="number" value="${skillInstance.level}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: skillInstance, field: 'type', 'error')} required">
	<label for="type">
		<g:message code="skill.type.label" default="Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="type" from="${org.eos.research.SkillType?.values()}" keys="${org.eos.research.SkillType.values()*.name()}" required="" value="${skillInstance?.type?.name()}" />

</div>

<div class="fieldcontain ${hasErrors(bean: skillInstance, field: 'usedOnEvent', 'error')} ">
	<label for="usedOnEvent">
		<g:message code="skill.usedOnEvent.label" default="Used On Event" />
		
	</label>
	<g:checkBox name="usedOnEvent" value="${skillInstance?.usedOnEvent}" />

</div>

grails-app/views/skill/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'skill.label', default: 'Skill')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-skill" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-skill" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${skillInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${skillInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:skillInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/skill/edit.gsp
<%@ page import="org.eos.research.Skill" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'skill.label', default: 'Skill')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-skill" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-skill" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${skillInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${skillInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:skillInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${skillInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/skill/index.gsp
<%@ page import="org.eos.research.Skill" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'skill.label', default: 'Skill')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-skill" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-skill" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="level" title="${message(code: 'skill.level.label', default: 'Level')}" />
					
						<g:sortableColumn property="type" title="${message(code: 'skill.type.label', default: 'Type')}" />
					
						<g:sortableColumn property="usedOnEvent" title="${message(code: 'skill.usedOnEvent.label', default: 'Used On Event')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${skillInstanceList}" status="i" var="skillInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${skillInstance.id}">${fieldValue(bean: skillInstance, field: "level")}</g:link></td>
					
						<td>${fieldValue(bean: skillInstance, field: "type")}</td>
					
						<td><g:formatBoolean boolean="${skillInstance.usedOnEvent}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${skillInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/skill/show.gsp
<%@ page import="org.eos.research.Skill" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'skill.label', default: 'Skill')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-skill" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-skill" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list skill">
			
				<g:if test="${skillInstance?.level}">
				<li class="fieldcontain">
					<span id="level-label" class="property-label"><g:message code="skill.level.label" default="Level" /></span>
					
						<span class="property-value" aria-labelledby="level-label"><g:fieldValue bean="${skillInstance}" field="level"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${skillInstance?.type}">
				<li class="fieldcontain">
					<span id="type-label" class="property-label"><g:message code="skill.type.label" default="Type" /></span>
					
						<span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${skillInstance}" field="type"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${skillInstance?.usedOnEvent}">
				<li class="fieldcontain">
					<span id="usedOnEvent-label" class="property-label"><g:message code="skill.usedOnEvent.label" default="Used On Event" /></span>
					
						<span class="property-value" aria-labelledby="usedOnEvent-label"><g:formatBoolean boolean="${skillInstance?.usedOnEvent}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:skillInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${skillInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>