grails-app/domain/org/eos/research/Character.groovy
package org.eos.research

class Character {

    long id
    String name
    Set<Skill> skills = new HashSet<>()

    static hasMany = [skills: Skill]

    static constraints = {
    }

    Character addSkill(SkillType type, int level) {
        Skill skill = new Skill(type: type, level: level).save()
        skills.add(skill)
        return this
    }
}

grails-app/controllers/org/eos/research/CharacterController.groovy
package org.eos.research


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CharacterController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Character.list(params), model: [characterInstanceCount: Character.count()]
    }

    def show(Character characterInstance) {
        respond characterInstance
    }

    def create() {
        respond new Character(params)
    }

    @Transactional
    def save(Character characterInstance) {
        if (characterInstance == null) {
            notFound()
            return
        }

        if (characterInstance.hasErrors()) {
            respond characterInstance.errors, view: 'create'
            return
        }

        characterInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'character.label', default: 'Character'), characterInstance.id])
                redirect characterInstance
            }
            '*' { respond characterInstance, [status: CREATED] }
        }
    }

    def edit(Character characterInstance) {
        respond characterInstance
    }

    @Transactional
    def update(Character characterInstance) {
        if (characterInstance == null) {
            notFound()
            return
        }

        if (characterInstance.hasErrors()) {
            respond characterInstance.errors, view: 'edit'
            return
        }

        characterInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Character.label', default: 'Character'), characterInstance.id])
                redirect characterInstance
            }
            '*' { respond characterInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Character characterInstance) {

        if (characterInstance == null) {
            notFound()
            return
        }

        characterInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Character.label', default: 'Character'), characterInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'character.label', default: 'Character'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/character/_form.gsp
<%@ page import="org.eos.research.Character" %>



<div class="fieldcontain ${hasErrors(bean: characterInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="character.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${characterInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: characterInstance, field: 'skills', 'error')} ">
	<label for="skills">
		<g:message code="character.skills.label" default="Skills" />
		
	</label>
	<g:select name="skills" from="${org.eos.research.Skill.list()}" multiple="multiple" optionKey="id" size="5" value="${characterInstance?.skills*.id}" class="many-to-many"/>

</div>

grails-app/views/character/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'character.label', default: 'Character')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-character" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-character" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${characterInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${characterInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:characterInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/character/edit.gsp
<%@ page import="org.eos.research.Character" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'character.label', default: 'Character')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-character" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-character" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${characterInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${characterInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:characterInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${characterInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/character/index.gsp
<%@ page import="org.eos.research.Character" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'character.label', default: 'Character')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-character" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-character" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'character.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${characterInstanceList}" status="i" var="characterInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${characterInstance.id}">${fieldValue(bean: characterInstance, field: "name")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${characterInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/character/show.gsp
<%@ page import="org.eos.research.Character" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'character.label', default: 'Character')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-character" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-character" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list character">
			
				<g:if test="${characterInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="character.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${characterInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${characterInstance?.skills}">
				<li class="fieldcontain">
					<span id="skills-label" class="property-label"><g:message code="character.skills.label" default="Skills" /></span>
					
						<g:each in="${characterInstance.skills}" var="s">
						<span class="property-value" aria-labelledby="skills-label"><g:link controller="skill" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:characterInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${characterInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>